const { contextBridge, ipcRenderer } = require('electron');

function on(channel, callback) {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('ph', {
  settings: {
    setLanguage: (language) => ipcRenderer.invoke('settings:language', language),
  },
  data: {
    get: () => ipcRenderer.invoke('data:get'),
    save: (data) => ipcRenderer.invoke('data:save', data),
    export: () => ipcRenderer.invoke('data:export'),
    import: () => ipcRenderer.invoke('data:import'),
    onChanged: (callback) => on('data:changed', callback),
  },
  sites: {
    open: (id) => ipcRenderer.invoke('site:open', id),
    hide: () => ipcRenderer.invoke('site:hide'),
    action: (id, action) => ipcRenderer.invoke('site:action', id, action),
    setClean: (id, enabled) => ipcRenderer.invoke('site:set-clean', id, enabled),
    clearData: (id) => ipcRenderer.invoke('site:clear-data', id),
    saveCustom: (site) => ipcRenderer.invoke('site:custom-upsert', site),
    removeCustom: (id) => ipcRenderer.invoke('site:custom-remove', id),
    reorderCustom: (ids) => ipcRenderer.invoke('site:custom-reorder', ids),
    onState: (callback) => on('site:state', callback),
  },
  credentials: {
    status: () => ipcRenderer.invoke('credentials:status'),
    save: (credential) => ipcRenderer.invoke('credentials:save', credential),
    remove: (siteId) => ipcRenderer.invoke('credentials:remove', siteId),
    fill: (siteId) => ipcRenderer.invoke('credentials:fill', siteId),
    discardUnreadable: () => ipcRenderer.invoke('credentials:discard-unreadable'),
    onChanged: (callback) => on('credentials:changed', callback),
  },
  xinlv: {
    status: () => ipcRenderer.invoke('xinlv:status'),
    ping: () => ipcRenderer.invoke('xinlv:ping'),
    login: (input) => ipcRenderer.invoke('xinlv:login', input),
    register: (input) => ipcRenderer.invoke('xinlv:register', input),
    logout: () => ipcRenderer.invoke('xinlv:logout'),
    profile: () => ipcRenderer.invoke('xinlv:profile'),
    list: (input) => ipcRenderer.invoke('xinlv:list', input),
    add: (input) => ipcRenderer.invoke('xinlv:add', input),
    edit: (input) => ipcRenderer.invoke('xinlv:edit', input),
    remove: (uuid) => ipcRenderer.invoke('xinlv:remove', uuid),
    sync: (input) => ipcRenderer.invoke('xinlv:sync', input),
    catalog: () => ipcRenderer.invoke('xinlv:catalog'),
    recommend: (mood) => ipcRenderer.invoke('xinlv:recommend', mood),
    chat: (message) => ipcRenderer.invoke('xinlv:chat', message),
    history: () => ipcRenderer.invoke('xinlv:history'),
    proactive: (since) => ipcRenderer.invoke('xinlv:proactive', since),
    clearChat: () => ipcRenderer.invoke('xinlv:clear-chat'),
    // 后台同步拉到新记录（别的设备/网页端改的）：界面据此静默刷新。
    onChanged: (callback) => on('xinlv:changed', callback),
  },
  // phix 统一账号 · 云同步：与 Pinghe Launcher Lite 共用同一账号与同一份数据文件。
  // 每个方法都回 { ok, data } 或 { ok:false, error, code }，界面直接判 ok。
  phix: {
    status: () => ipcRenderer.invoke('phix:status'),
    serverCandidates: () => ipcRenderer.invoke('phix:server-candidates'),
    restore: () => ipcRenderer.invoke('phix:restore'),
    profile: () => ipcRenderer.invoke('phix:profile'),
    saveProfile: (input) => ipcRenderer.invoke('phix:save-profile', input),
    ping: (server) => ipcRenderer.invoke('phix:ping', server),
    register: (input) => ipcRenderer.invoke('phix:register', input),
    login: (input) => ipcRenderer.invoke('phix:login', input),
    unlock: (passphrase) => ipcRenderer.invoke('phix:unlock', passphrase),
    logout: () => ipcRenderer.invoke('phix:logout'),
    sync: (input) => ipcRenderer.invoke('phix:sync', input),
    syncPreview: () => ipcRenderer.invoke('phix:sync-preview'),
    conflicts: () => ipcRenderer.invoke('phix:conflicts'),
    trustKey: () => ipcRenderer.invoke('phix:trust-key'),
    devices: () => ipcRenderer.invoke('phix:devices'),
    // P3：会话列表（一次登录 = 一台设备）与注销某台 / 注销除本机外全部
    sessions: () => ipcRenderer.invoke('phix:sessions'),
    revokeSession: (input) => ipcRenderer.invoke('phix:session-revoke', input),
    saveSettings: (input) => ipcRenderer.invoke('phix:settings-save', input),
    setPassphrase: (input) => ipcRenderer.invoke('phix:set-passphrase', input),
    useLoginPassword: (input) => ipcRenderer.invoke('phix:use-login-password', input),
    changePassword: (input) => ipcRenderer.invoke('phix:change-password', input),
    openDataDir: () => ipcRenderer.invoke('phix:open-data-dir'),
  },
  ai: {
    configure: (config) => ipcRenderer.invoke('ai:configure', config),
    chat: (messages, options) => ipcRenderer.invoke('ai:chat', messages, options),
    chatStream: (requestId, messages, options) => ipcRenderer.invoke('ai:chat-stream', requestId, messages, options),
    history: {
      get: () => ipcRenderer.invoke('ai:history-get'),
      saveSession: (input) => ipcRenderer.invoke('ai:history-save', input),
      removeSession: (id) => ipcRenderer.invoke('ai:history-remove', id),
      saveMemory: (input) => ipcRenderer.invoke('ai:memory-save', input),
      removeMemory: (id) => ipcRenderer.invoke('ai:memory-remove', id),
    },
    workspace: {
      get: () => ipcRenderer.invoke('ai:workspace-get'),
      pick: () => ipcRenderer.invoke('ai:workspace-pick'),
      create: (name) => ipcRenderer.invoke('ai:workspace-create', name),
      set: (workspace) => ipcRenderer.invoke('ai:workspace-set', { workspace }),
      clear: () => ipcRenderer.invoke('ai:workspace-clear'),
    },
    cancelStream: (requestId) => ipcRenderer.invoke('ai:cancel-stream', requestId),
    status: () => ipcRenderer.invoke('ai:status'),
    controlInfo: () => ipcRenderer.invoke('ai:control-info'),
    previewEduPage: () => ipcRenderer.invoke('ai:edupage-preview'),
    confirmAction: (proposalId) => ipcRenderer.invoke('ai:confirm-action', proposalId),
    cancelAction: (proposalId) => ipcRenderer.invoke('ai:cancel-action', proposalId),
    deploymentState: () => ipcRenderer.invoke('ai:deployment-state'),
    deployLocal: () => ipcRenderer.invoke('ai:deploy-local'),
    cancelDeployment: () => ipcRenderer.invoke('ai:cancel-deployment'),
    showDeploymentLog: () => ipcRenderer.invoke('ai:show-deployment-log'),
    onDeployment: (callback) => on('ai:deployment-state', callback),
    onStream: (callback) => on('ai:stream', callback),
    onStatus: (callback) => on('ai:status', callback),
    onCommand: (callback) => on('ai:command', callback),
  },
  aiAttachments: {
    pick: () => ipcRenderer.invoke('ai-attachments:pick'),
    remove: (id) => ipcRenderer.invoke('ai-attachments:remove', id),
  },
  dictionary: {
    info: () => ipcRenderer.invoke('dictionary:info'),
    lookup: (query) => ipcRenderer.invoke('dictionary:lookup', query),
  },
  vocabulary: {
    configureAdvisor: (input) => ipcRenderer.invoke('vocabulary:configure-advisor', input),
    coach: (input) => ipcRenderer.invoke('vocabulary:coach', input),
    cancelCoach: (input) => ipcRenderer.invoke('vocabulary:cancel-coach', input),
    prefetchBatch: (input) => ipcRenderer.invoke('vocabulary:prefetch-batch', input),
    prepareBatch: (input) => ipcRenderer.invoke('vocabulary:prepare-batch', input),
    startRecall: (input) => ipcRenderer.invoke('vocabulary:start-recall', input),
    checkAdvisor: (input) => ipcRenderer.invoke('vocabulary:check-advisor', input),
    importReadingDocument: () => ipcRenderer.invoke('vocabulary:import-reading-document'),
    cancelPrepareBatch: (input) => ipcRenderer.invoke('vocabulary:cancel-prepare-batch', input),
    dueCount: () => ipcRenderer.invoke('vocabulary:due-count'),
    onChanged: (callback) => on('vocabulary:changed', callback),
    checkExpression: (input) => ipcRenderer.invoke('vocabulary:check-expression', input),
    catalogWords: (id, limit) => ipcRenderer.invoke('vocabulary:catalog-words', id, limit),
    placementSubmit: (input) => ipcRenderer.invoke('vocabulary:placement-submit', input),
    get: (subject) => ipcRenderer.invoke('vocabulary:get', subject),
    saveReading: (input) => ipcRenderer.invoke('vocabulary:save-reading', input),
    finishReading: (input) => ipcRenderer.invoke('vocabulary:finish-reading', input),
    removeReading: (id) => ipcRenderer.invoke('vocabulary:remove-reading', id),
    add: (entries) => ipcRenderer.invoke('vocabulary:add', entries),
    addStarter: (subject) => ipcRenderer.invoke('vocabulary:starter', subject),
    review: (input) => ipcRenderer.invoke('vocabulary:review', input),
    undo: () => ipcRenderer.invoke('vocabulary:undo'),
    update: (input) => ipcRenderer.invoke('vocabulary:update', input),
    remove: (id) => ipcRenderer.invoke('vocabulary:remove', id),
    configure: (input) => ipcRenderer.invoke('vocabulary:configure', input),
    extract: (text) => ipcRenderer.invoke('vocabulary:extract', text),
    importText: (text) => ipcRenderer.invoke('vocabulary:import-text', text),
    exportFile: () => ipcRenderer.invoke('vocabulary:export'),
    importFile: () => ipcRenderer.invoke('vocabulary:import'),
  },
  school: {
    get: (options) => ipcRenderer.invoke('school:get', options),
    sync: (source, options) => ipcRenderer.invoke('school:sync', source, options),
    login: (source, options) => ipcRenderer.invoke('school:login', source, options),
    preferences: (input) => ipcRenderer.invoke('school:preferences', input),
    importPlan: () => ipcRenderer.invoke('school:import-plan'),
    sharedAccounts: () => ipcRenderer.invoke('school:shared-accounts'),
    importSharedAccounts: () => ipcRenderer.invoke('school:import-shared-accounts'),
    exportSharedAccounts: () => ipcRenderer.invoke('school:export-shared-accounts'),
    course: (id) => ipcRenderer.invoke('school:course', id),
    discussions: (courseId) => ipcRenderer.invoke('school:discussions', courseId),
    discussion: (courseId, id) => ipcRenderer.invoke('school:discussion', courseId, id),
    task: (courseId, id) => ipcRenderer.invoke('school:task', courseId, id),
    ibOverview: (kind) => ipcRenderer.invoke('school:ib-overview', kind),
    // 通知 / 待办（ManageBac）：未读数 + 待办条目（与网页端同一口径）
    notifications: () => ipcRenderer.invoke('school:notifications'),
    openUrl: (url) => ipcRenderer.invoke('school:open-url', url),
    // 导出课表（CSV 文本 / PNG dataURL）：主进程弹保存对话框再落盘。
    exportTimetable: (input) => ipcRenderer.invoke('school:export-timetable', input),
    onPlanImported: (callback) => on('school:plan-imported', callback),
    onSynced: (callback) => on('school:synced', callback),
  },
  mail: {
    status: () => ipcRenderer.invoke('mail:status'),
    list: (options) => ipcRenderer.invoke('mail:list', options),
    read: (uid) => ipcRenderer.invoke('mail:read', uid),
    contacts: () => ipcRenderer.invoke('mail:contacts'),
    harvestContacts: (options) => ipcRenderer.invoke('mail:harvestContacts', options),
    download: (input) => ipcRenderer.invoke('mail:download', input),
    // 内嵌图片 / 转发带原附件用：只回字节，不弹保存对话框。
    downloadBytes: (input) => ipcRenderer.invoke('mail:downloadBytes', input),
    // 正文里的外部图片：由主进程取字节（沙箱 iframe 里直接 <img src="https://…"> 加载不出来）
    fetchImage: (input) => ipcRenderer.invoke('mail:fetchImage', input),
    openLink: (input) => ipcRenderer.invoke('mail:openLink', input),
    send: (draft) => ipcRenderer.invoke('mail:send', draft),
    onCleared: (callback) => on('mail:cleared', callback),
  },
  calendar: {
    chooseFiles: () => ipcRenderer.invoke('calendar:choose-files'),
    openFile: (filePath) => ipcRenderer.invoke('calendar:open-file', filePath),
    get: () => ipcRenderer.invoke('calendar:get'),
    save: (input) => ipcRenderer.invoke('calendar:save', input),
    remove: (id) => ipcRenderer.invoke('calendar:remove', id),
  },
  ib: {
    commandCatalog: () => ipcRenderer.invoke('ib:command-catalog'),
  },
  system: {
    version: () => ipcRenderer.invoke('system:version'),
    hardware: () => ipcRenderer.invoke('system:hardware'),
    openUrl: (url) => ipcRenderer.invoke('system:open-url', url),
    showData: () => ipcRenderer.invoke('system:show-data'),
    dataChoice: () => ipcRenderer.invoke('system:data-choice'),
    shareDataWithLite: () => ipcRenderer.invoke('system:data-share-lite'),
    useOwnDataFolder: () => ipcRenderer.invoke('system:data-use-own'),
    notify: (payload) => ipcRenderer.invoke('system:notify', payload),
    splashState: () => ipcRenderer.invoke('system:splash-state'),
    onSplashProgress: (callback) => on('splash:progress', callback),
    onSplashDone: (callback) => on('splash:done', callback),
  },
  shortcuts: {
    register: () => ipcRenderer.invoke('shortcuts:register'),
    onAction: (callback) => on('shortcut:action', callback),
    onResults: (callback) => on('shortcut:results', callback),
  },
  window: {
    minimize: () => ipcRenderer.send('window:minimize'),
    maximize: () => ipcRenderer.send('window:maximize'),
    close: () => ipcRenderer.send('window:close'),
  },
  onReady: (callback) => on('app:ready', callback),
  //: 命令行 `--ph-force-onboarding`：让首启引导再出现一次（只影响这一次运行）。
  onForceOnboarding: (callback) => on('app:force-onboarding', callback),
  onTrayNavigate: (callback) => on('tray:navigate', callback),
  //: 发现新版本：主进程只**通知**，由界面弹卡片让用户选（绝不自动更新）。
  onUpdateAvailable: (callback) => on('app:update-available', callback),
  //: 用户在卡片上选完：'cancel'（这次先不选）/ 'skip'（跳过本版本）/ 'update'（开始更新）。
  updateChoice: (choice) => ipcRenderer.invoke('app:update-choice', choice),
  //: 更新进度（下载中/替换中/失败原因），供卡片显示状态。
  onUpdateProgress: (callback) => on('app:update-progress', callback),
});
